### ISSUE TITLE
Refactor out Copy and Inject_Attrs Transforms.

### ISSUE THREAD

**Issue by norlandrhagen** [leap-stc/proto_feedstock#31]
Should we move these two transforms into : https://github.com/leap-stc/leap-data-management-utils?
cc @jbusecke

**Comment by jbusecke** [comment]
Yeah that was my plan eventually!

**Comment by jbusecke** [comment]
Should this be part of #27 ? I think it fits thematically.

**Comment by jbusecke** [comment]
Closed via #32
